[project]
name = "gen-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kuheli Bera", email = "kuhelibera31@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "langchain>=1.4.0",
]

[project.scripts]
gen-ai = "gen_ai:main"

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"
